add xscreensaver v6.05
Signed-off-by: Jeffrey Merkey <jeffmerkey@gmail.com>

diff --git a/OSX/Makefile b/OSX/Makefile
--- a/OSX/Makefile
+++ b/OSX/Makefile
@@ -1,14 +1,6 @@
-# XScreenSaver for MacOS X, Copyright © 2006-2021 Jamie Zawinski.
+# XScreenSaver for MacOS X, Copyright © 2006-2022 Jamie Zawinski.
 
-XCODE_APP = /Applications/Xcode.app
-
-# To build savers that will run on MacOS 10.6 and 10.7, Xcode 5.0.2 must
-# be used (as that's the latest version of Xcode that ships with a version
-# of clang that implements "-fobjc-gc").  However, Xcode 5.0.2 will not
-# launch on MacOS 10.11 or later.
-#
-# XCODE_APP = /Applications/Xcode-5.0.2.app
-
+XCODE_APP  = /Applications/Xcode.app
 TARGETS    = All Savers
 #ARCH      = -arch i386 -arch x86_64 ONLY_ACTIVE_ARCH=NO
 CERT	   = 'Developer ID Installer: Jamie Zawinski (4627ATJELP)'
@@ -40,17 +32,24 @@ distclean:
 distdepend:: Sparkle.framework
 distdepend:: update_plist_version
 
-debug: distdepend
+_debug: distdepend
 	$(XCODEBUILD) $(ARCH) -target "$(TARGETS)" -configuration Debug   build
 
-release:: distdepend
+_release:: distdepend
 	$(XCODEBUILD) $(ARCH) -target "$(TARGETS)" -configuration Release build
 
-release:: check_versions
+_release:: check_versions
+
+debug::
+	$(MAKE2) _debug > /dev/null
+
+release::
+	$(MAKE2) _release > /dev/null
+
 
 Sparkle.framework:
 	rm -rf bin sparkle-bin
-	tar -vxjf ../archive/Sparkle-1.21.2.tar.bz2 \
+	tar -vxjf ../archive/Sparkle-1.27.0.tar.xz \
 	  --exclude CHANGELOG \
 	  --exclude LICENSE \
 	  --exclude SampleAppcast.xml \
@@ -59,29 +58,34 @@ Sparkle.framework:
 	mv bin sparkle-bin
 
 # Download and resize images from jwz.org.
-# This saves us having to include 4MB of images in the tar file
-# that will only be used by a vast minority of people building
-# from source.
-# update-info-plist.pl runs this as needed.
-# Might be better to do this with curl, since that is installed by default.
+# Largely duplicated in android/Makefile.
+# This saves us having to include 4MB of images in the tar file that
+# will only be used by a vast minority of people building from source.
+# update-info-plist.pl runs "make" to do this as needed.
 
 BASE = xscreensaver/screenshots/
-URL = https://www.jwz.org/$(BASE)
+URL = https://cdn.jwz.org/$(BASE)
 
 # I find wget easier to deal with, but curl is usually installed by default.
 #WGET = wget -q -U xscreensaver-build-osx --content-on-error=0 -O-
-WGET = curl -s -A xscreensaver-build-osx -f
+WGET = curl -sL -A xscreensaver-build-osx -f
 
+# ImageMagick isn't installed by default, but neither is anything similar.
+#
 # Apple savers have "thumbnail.png" at 90x58 and "thumbnail@2x.png" at 180x116.
 # System Preferences stretches those to fill a bordered 170x105 frame.
-# These args take our source images (usually 200x150) and fits them into a
-# 180x116 box, cropping either horizontally or vertically as needed.
-# It also makes the alpha mask have rounded corners.
+#
+# This recipe takes our source images (usually 200x150) and fits them into
+# a 180x116 box, cropping either horizontally or vertically as needed, with
+# rounded corners in the alpha mask.
 #
 THUMB_SIZE=180x116
+THUMB_CURVE=15
 CVT  = -thumbnail $(THUMB_SIZE)'^' -gravity center -extent $(THUMB_SIZE) \
      \( +clone  -alpha extract \
-        -draw 'fill black polygon 0,0 0,6 6,0 fill white circle 6,6 6,0' \
+        -draw \
+          'fill black polygon 0,0 0,$(THUMB_CURVE) $(THUMB_CURVE),0 \
+           fill white circle $(THUMB_CURVE),$(THUMB_CURVE) $(THUMB_CURVE),0' \
         \( +clone -flip \) -compose Multiply -composite \
         \( +clone -flop \) -compose Multiply -composite \
      \) -alpha off -compose CopyOpacity -composite \
@@ -96,7 +100,6 @@ $(THUMBDIR)/%.png:
 	FILE2="$@" ;							\
 	TMP="$$FILE2".tmp ;						\
 	URL="$(URL)$$FILE1" ;						\
-	URL2="$(URL)retired/$$FILE1" ;					\
 	if [ ! -d $(THUMBDIR) ]; then mkdir -p $(THUMBDIR) ; fi ;	\
 	rm -f "$$FILE2" "$$TMP" ;					\
 	set +e ;							\
@@ -105,10 +108,6 @@ $(THUMBDIR)/%.png:
 	else								\
 	  echo "downloading $$URL..." ;					\
 	  $(WGET) "$$URL" > "$$TMP" ;					\
-	  if [ ! -s "$$TMP" ]; then					\
-	    echo "downloading $$URL2..." ;				\
-	    $(WGET) "$$URL2" > "$$TMP" ;				\
-	  fi ;								\
 	  if [ ! -s "$$TMP" ]; then					\
 	    rm -f "$$TMP" ;						\
 	    echo "failed: $$URL" ;					\
@@ -166,63 +165,6 @@ check_versions:
   exit $$RESULT
 
 
-check_gc:
-	@\
-  DIR="build/Release" ;							\
-  RESULT=0 ;								\
-  for S in "$$DIR/"*.saver ; do						\
-   SS=`echo "$$S" | sed -e 's@^.*/@@' -e 's/.saver$$//'` ;		\
-   D="$$S/Contents/MacOS/$$SS" ;					\
-   V=`otool -s __DATA __objc_imageinfo "$$D"				\
-      | grep ' 00 02 00 '` ;						\
-   if [ -z "$$V" ]; then						\
-     echo "$$S does not have GC enabled" ;				\
-     RESULT=1 ;								\
-   fi ;									\
-  done ;								\
-									\
-  for D in "$$DIR"/webcollage-helper					\
-	   "$$DIR"/*.saver/Contents/*/webcollage-helper			\
-	   "$$DIR"/*.app/Contents/*/XScreenSaverUpdater			\
-   ; do									\
-   V=`otool -s __DATA __objc_imageinfo "$$D"				\
-      | grep ' 00 02 00 '` ;						\
-   if [ ! -z "$$V" ]; then						\
-     echo "$$D has GC enabled" ;					\
-     RESULT=1 ;								\
-   fi ;									\
-  done ;								\
-									\
-  if [ "$$RESULT" = 0 ]; then echo "GC enabled" ; fi ;			\
-  exit $$RESULT
-
-
-check_coretext:
-	@\
-  DIR="build/Release" ;							\
-  RESULT=0 ;								\
-  for S in "$$DIR/"*.{saver,app} ; do					\
-   SS=`echo "$$S" | sed -e 's@^.*/@@' -e 's/[.][a-z]*$$//'` ;		\
-   D="$$S/Contents/MacOS/$$SS" ;					\
-   FF=`otool -l "$$D"							\
-      | fgrep '/CoreText.framework/'					\
-      | sed -n 's/^ *name \([^ ]*\).*$$/\1/p'` ;			\
-   if [ -z "$$FF" ] ; then						\
-     echo "$$S not linked with CoreText" >/dev/null ;			\
-   else 								\
-     OK=`echo "$$FF" | fgrep -v '/ApplicationServices.framework/'` ;	\
-     if [ ! -z "$$OK" ]; then						\
-       echo "$$S is linked with the wrong CoreText: $$FF" ;		\
-       RESULT=1 ;							\
-     else								\
-       echo "$$S linked right: $$FF" >/dev/null ;			\
-     fi ;								\
-   fi ;									\
-  done ;								\
-  if [ "$$RESULT" = 0 ]; then echo "CoreText linked correctly" ; fi ;	\
-  exit $$RESULT
-
-
 # Arrrrgh
 ios-function-table.m::
 	@./build-fntable.pl build/Debug-iphonesimulator/XScreenSaver.app $@
@@ -273,24 +215,43 @@ test_sig::
   BASE="xscreensaver-$$V" ;						    \
   OUTDIR="../archive" ;							    \
   DMG="$$OUTDIR/$$BASE.dmg" ;						    \
-  SIG=`sed -n 's/^.*dsaSignature="\(.*\)".*/\1/p' updates.xml` ;	    \
-  PUB="sparkle_dsa_pub.pem" ;						    \
+  SIG1=`sed -n 's/^.*dsaSignature="\(.*\)".*/\1/p' updates.xml` ;	    \
+  SIG2=`sed -n  's/^.*edSignature="\(.*\)".*/\1/p' updates.xml` ;	    \
+  PUB1="sparkle_dsa_pub.pem" ;						    \
   NN="t.$$$$" ;								    \
   SIGB=/tmp/$$NN.sig ;							    \
   HASH=/tmp/$$NN.hash ;							    \
   rm -f "$$SIGB" "$$HASH" ;						    \
-  if ( echo "$$SIG" | grep -qi ERROR ); then				    \
-    echo "No signature in updates.xml" >&2 ; exit 1 ;			    \
+  if ( echo "$$SIG1" | grep -qi ERROR ); then				    \
+    echo "No DSA signature in updates.xml" >&2 ; exit 1 ;		    \
   fi ;									    \
-  echo "$$SIG " | base64 -D  > "$$SIGB" ;				    \
+  if ( echo "$$SIG2" | grep -qi ERROR ); then				    \
+    echo "No ED signature in updates.xml" >&2 ; exit 1 ;		    \
+  fi ;									    \
+									    \
   set -e ;								    \
+  echo "$$SIG1 " | base64 -D  > "$$SIGB" ;				    \
   for OPENSSL in /usr/bin/openssl /opt/local/bin/openssl ; do		    \
     $$OPENSSL dgst -sha1 -binary  < "$$DMG"  > "$$HASH" ;		    \
-    /bin/echo -n "$$OPENSSL	`$$OPENSSL version`:	" ;		    \
-    $$OPENSSL dgst -sha1 -verify "$$PUB" -signature "$$SIGB" "$$HASH" ;	    \
+    /bin/echo -n "DSA $$OPENSSL    	`$$OPENSSL version`:	" ;	    \
+    $$OPENSSL dgst -sha1 -verify "$$PUB1" -signature "$$SIGB" "$$HASH" ;    \
   done ;								    \
+  echo "Warning: not verifying edSignature because I don't know how..." ;   \
+									    \
   rm -f "$$SIGB" "$$HASH" ;						    \
 
+
+# As of Xcode 13, I think it's no longer possible to check signatures on the
+# saver bundles: they must be signed with "Developer ID Application" but as
+# the individual savers are not notarized, "spctl --assess --type install"
+# reports "rejected, Unnotarized Developer ID".
+#
+# Also, after running "productsign" on the pkg, "codesign" reports that it
+# is unsigned, so WTF?
+#
+# "codesign -vv --deep --strict" complains: "resource fork, Finder
+# information, or similar detritus not allowed".  Maybe it is complaining
+# about the "Icon\r" file?
 
 build/Release/installer.pkg: installer.rtf installer.xml installer.sh installer.png ../utils/version.h
 	@\
@@ -321,15 +282,17 @@ build/Release/installer.pkg: installer.rtf installer.xml installer.sh installer.
 	       --package-path "$$STAGE" --version "$$V" "$$PRODUCT" ;	\
 									\
   productsign --sign $(CERT) "$$PRODUCT" "$$FINAL" ;			\
-  spctl --assess --verbose=4 --type install "$$FINAL" ;			\
+									\
+  if false; then							\
+    spctl --assess --verbose=4 --type install "$$FINAL" ;		\
+  fi ;									\
 									\
   rm -rf "$$STAGE" ;							\
 
 
-dmg:: distdepend check_versions check_coretext
-#dmg:: check_gc
+dmg:: distdepend check_versions
 dmg:: build/Release/installer.pkg
-dmg:: _dmg notarize
+dmg:: _dmg notarize staple updates.xml
 
 _dmg::
 	@								      \
@@ -412,10 +375,18 @@ _dmg::
   sudo chown -R root:wheel "$$STAGE/"* ;				      \
 									      \
   echo "Checking signatures..." ;					      \
-  spctl --assess --type install "$$PKG" ;				      \
-  spctl --assess --type execute "$$SRC/XScreenSaverUpdater.app" ;	      \
-  spctl --assess --type execute "$$DST/"*.app ;				      \
-  spctl --assess --type install "$$DST/"*.saver ;			      \
+  if false; then							      \
+    spctl --assess --type install "$$PKG" ;				      \
+    spctl --assess --type execute "$$SRC/XScreenSaverUpdater.app" ;	      \
+    spctl --assess --type execute "$$DST/"*.app ;			      \
+    spctl --assess --type install "$$DST/"*.saver ;			      \
+  else									      \
+    true codesign -vv --deep --strict "$$PKG" ;				      \
+    codesign -vv --deep --strict "$$SRC/XScreenSaverUpdater.app" ;	      \
+    true codesign -vv --deep --strict "$$DST/"*.app ;			      \
+    true codesign -vv --deep --strict "$$DST/"*.saver ;			      \
+  fi ;									      \
+									      \
   set -x ;								      \
 									      \
   hdiutil makehybrid -quiet -ov -hfs -hfs-volume-name "$$VOLNAME"	      \
@@ -429,7 +400,11 @@ _dmg::
   rm -f "$$TMPDMG" ;							      \
 									      \
   codesign --sign $(CERT2) "$$DMG" ;					      \
-  spctl --assess --type install "$$DMG" ;				      \
+  if false; then							      \
+    spctl --assess --type install "$$DMG" ;				      \
+  else									      \
+    codesign -vvv --deep --strict "$$DMG" ;				      \
+  fi ;									      \
 									      \
   ls -ldhgF "$$DMG" ;							      \
 
@@ -441,20 +416,25 @@ _dmg::
 #  - Name: "altool-notarizer", Account: "jwz@jwz.org",
 #    Pass: the one you just generated.
 #
-# "make notarize", which will upload the DMG (slow).
-# "notarize_wait" waits for the response to be ready (takes 5+ minutes).
-# Only once that has arrived can we "staple" it onto the DMG.
+# As of Xcode 13, "altool" is obsolete because of course it is.
+# The new way is "notarytool".
 #
-# https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution/customizing_the_notarization_workflow?language=objc
+# "make notarize" will upload the DMG (slow).
 #
 # Note that if Sparkle.framework/.../Autoupdate.app is not independently
 # signed, it won't pass. I had to add a build phase for that.
 #
-NOTARGS=-u "jwz@jwz.org" -p "@keychain:altool-notarizer"
+# - xcrun notarytool store-credentials --apple-id jwz@jwz.org
+#   - Profile name: altool-notarizer
+#   - App-specific password: [the above]
+#   - Developer Team ID: 4627ATJELP
+# - Credentials saved to Keychain.
+#   To use them, specify `--keychain-profile "altool-notarizer"
+#
+#NOTARGS=-u "jwz@jwz.org" -p "@keychain:altool-notarizer"
 
 
 # Send a notarization request, and then wait for the result.
-# Staple once the results are in.
 #
 notarize::
 	@								      \
@@ -464,52 +444,39 @@ notarize::
   BASE="xscreensaver-$$V" ;						      \
   OUTDIR="../archive" ;							      \
   DMG="$$OUTDIR/$$BASE.dmg" ;						      \
-  CMD='xcrun altool --notarize-app --primary-bundle-id org.jwz.xscreensaver'; \
-  CMD="$$CMD --file $$DMG $(NOTARGS)" ;					      \
+  CMD="xcrun notarytool submit $$DMG" ;					      \
+  CMD="$$CMD --keychain-profile altool-notarizer" ;			      \
+  CMD="$$CMD --apple-id jwz@jwz.org --team-id 4627ATJELP --wait" ;	      \
   echo "+ $$CMD" ;  							      \
   echo "" ;								      \
   RET=`$$CMD` ;  							      \
   echo "$$RET";  							      \
   echo "" ;								      \
-  ID=`echo "$$RET" | sed -n 's/RequestUUID *= *\(.*\)/\1/p'` ;		      \
+  ID=`echo "$$RET" | sed -n 's/.*id: *\([^ ]*\).*/\1/p' | head -1` ;	      \
+  STATUS=`echo "$$RET" | sed -n 's/.*status: *\([^ .]*\).*/\1/p' | head -1` ; \
   if [ "x$$ID" = "x" ]; then						      \
-    echo "unparsable RequestUUID" ;					      \
+    echo "unparsable ID" ;						      \
     exit 1 ;								      \
-  else									      \
-    set -x ;								      \
-    export NOTARIZE_UUID="$$ID" ;					      \
-    $(MAKE2) notarize_wait staple updates.xml ;				      \
   fi ;									      \
+  if [ x"$$STATUS" != "xAccepted" ]; then				      \
+    echo "ERROR: Bad status: $$STATUS" ;				      \
+    echo "" ;								      \
+    CMD="xcrun notarytool log $$ID --keychain-profile altool-notarizer" ;     \
+    echo "+ $$CMD" ;  							      \
+    $$CMD ;								      \
+    exit 1 ;								      \
+  fi ;									      \
+  echo "Notarization success: $$STATUS" ;				      \
+  exit 0
 
 
-# Keep probing Apple's server until we have a result for this notarization.
-# We can't staple until the results are in.
+# Uploading the DMG to the notarizer generated a gatekeeper ticket for
+# each enclosed item.  Staple those tickets to the DMG file.
 #
-notarize_wait::
-	@if [ "x$$NOTARIZE_UUID" = "x" ]; then				      \
-	   echo "NOTARIZE_UUID is unset" ;				      \
-	   exit 1 ;							      \
-	 fi ;								      \
-	 CMD="xcrun altool --notarization-info $$NOTARIZE_UUID $(NOTARGS)" ;  \
-	 echo "+ $$CMD" ;						      \
-	 while true ; do						      \
-	   RET=`$$CMD` ;						      \
-	   STATUS=`echo "$$RET" | sed -n 's/^ *Status: *\(.*\)/\1/p'` ;	      \
-	   if [ "x$$STATUS" = 'xin progress' ]; then			      \
-	     echo " `date +%H:%M:%S` $$STATUS..." ;			      \
-	     sleep 15 ;							      \
-	   elif [ "x$$STATUS" = 'xsuccess' ]; then			      \
-	     echo "" ;							      \
-	     echo "$$RET" ;						      \
-	     echo "" ;							      \
-	     exit 0 ;							      \
-	   else								      \
-	     echo "" ;							      \
-	     echo "$$RET" ;						      \
-	     exit 1 ;							      \
-	   fi ;								      \
-	 done ;								      \
-
+# If we had uploaded a .zip, we would need to staple to the enclosed item
+# and re-generate the .zip, but I think we can staple directly to a DMG
+# without needing to re-generate it?
+#
 staple::
 	@								      \
   set -e ;								      \
@@ -521,11 +488,6 @@ staple::
   set -x ;								      \
   xcrun stapler staple "$$DMG" ;					      \
   xcrun stapler validate "$$DMG" ;					      \
-
-notarization_history::
-	xcrun altool --notarization-history 0 $(NOTARGS)
-	@echo 'now do: xcrun altool $(NOTARGS) --notarization-info <UUID>' ;  \
-	echo 'and wget the LogFileURL' ;				      \
 
 
 # When debugging, sometimes I have to reset the preferences for all
