add xscreensaver v5.43
Signed-off-by: Jeffrey Merkey <jeffmerkey@gmail.com>

diff --git a/OSX/Makefile b/OSX/Makefile
--- a/OSX/Makefile
+++ b/OSX/Makefile
@@ -12,6 +12,7 @@ XCODE_APP = /Applications/Xcode.app
 TARGETS    = All Savers
 #ARCH      = -arch i386 -arch x86_64 ONLY_ACTIVE_ARCH=NO
 CERT	   = 'Developer ID Installer: Jamie Zawinski (4627ATJELP)'
+CERT2	   = 'Developer ID Application: Jamie Zawinski (4627ATJELP)'
 PKGID	   = org.jwz.xscreensaver
 THUMBDIR   = build/screenshots
 XCODEBUILD = $(XCODE_APP)/Contents/Developer/usr/bin/xcodebuild
@@ -227,7 +228,7 @@ update_plist_version:
 
 updates.xml::
 	./updates.pl xscreensaver ../README ../archive ~/www/xscreensaver
-	@$(MAKE) test_sig
+	@$(MAKE) $(MAKEFLAGS) test_sig
 
 test_sig::
 	@								    \
@@ -242,6 +243,9 @@ test_sig::
   SIGB=/tmp/$$NN.sig ;							    \
   HASH=/tmp/$$NN.hash ;							    \
   rm -f "$$SIGB" "$$HASH" ;						    \
+  if ( echo "$$SIG" | grep -qi ERROR ); then				    \
+    echo "No signature in updates.xml" >&2 ; exit 1 ;			    \
+  fi ;									    \
   echo "$$SIG " | base64 -D  > "$$SIGB" ;				    \
   set -e ;								    \
   for OPENSSL in /usr/bin/openssl /opt/local/bin/openssl ; do		    \
@@ -286,7 +290,6 @@ build/Release/installer.pkg: installer.rtf installer.xml installer.sh installer.
   rm -rf "$$STAGE" ;							\
 
 
-# -format UDBZ saves 4% (~1.2 MB) over UDZO.
 dmg:: distdepend check_versions check_coretext
 #dmg:: check_gc
 dmg:: build/Release/installer.pkg
@@ -362,6 +365,10 @@ _dmg::
   mv "$$STAGE/bindist2.webloc" "$$STAGE/Get the Android Version.webloc" ;     \
 									      \
   set +x ;								      \
+									      \
+  echo "Chowning..." ;							      \
+  sudo chown -R root:wheel "$$STAGE/"* ;				      \
+									      \
   echo "Checking signatures..." ;					      \
   spctl --assess --type install "$$PKG" ;				      \
   spctl --assess --type execute "$$SRC/XScreenSaverUpdater.app" ;	      \
@@ -371,14 +378,20 @@ _dmg::
 									      \
   hdiutil makehybrid -quiet -ov -hfs -hfs-volume-name "$$VOLNAME"	      \
     -hfs-openfolder "$$STAGE" "$$STAGE" -o "$$TMPDMG" ;			      \
+  echo "Chowning back and deleting..." ;				      \
+  sudo chown -R `whoami` "$$STAGE/"* ;					      \
   rm -rf "$$STAGE" ;							      \
 									      \
   hdiutil convert -quiet -ov -format UDBZ -imagekey zlib-level=9	      \
     "$$TMPDMG" -o "$$DMG" ;						      \
   xattr -w com.apple.quarantine "0000;00000000;;" "$$DMG" ;		      \
   rm -f "$$TMPDMG" ;							      \
+									      \
+  codesign --sign $(CERT2) "$$DMG" ;					      \
+  spctl --assess --type install "$$DMG" ;				      \
+									      \
   ls -ldhgF "$$DMG" ;							      \
-  $(MAKE) notarize ;							      \
+  $(MAKE) $(MAKEFLAGS) notarize ;					      \
 
 
 # To set up notarization:
@@ -389,8 +402,8 @@ _dmg::
 #    Pass: the one you just generated.
 #
 # "make notarize", which will upload the DMG (slow).
-# A response will be emailed back in about an hour.
-# When that arrives, "make staple".
+# "notarize_wait" waits for the response to be ready (takes 5+ minutes).
+# Only once that has arrived can we "staple" it onto the DMG.
 #
 # https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution/customizing_the_notarization_workflow?language=objc
 #
@@ -412,12 +425,16 @@ notarize::
     --file "$$DMG" $(NOTARGS) ;						      \
   echo "" ;								      \
   sleep 3 ;								      \
-  $(MAKE) notarize_wait staple updates.xml
+  $(MAKE) $(MAKEFLAGS) notarize_wait staple updates.xml
 
 notarize_wait::
-	@while ( xcrun altool --notarization-history 0 $(NOTARGS) |	      \
+	@TODAY=`date +%Y-%m-%d` ;					      \
+	 while ( xcrun altool --notarization-history 0 $(NOTARGS) |	      \
+		 grep "$$TODAY" |					      \
 		 grep -q 'in progress' ); do				      \
 	  echo `date +%I:%M:` "waiting for notarization..." ;		      \
+	  xcrun altool --notarization-history 0 $(NOTARGS) |		      \
+		 grep "$$TODAY" ;					      \
 	  sleep 15 ;							      \
 	done ;								      \
 	echo '' ;							      \
@@ -433,12 +450,12 @@ staple::
   DMG="$$OUTDIR/$$BASE.dmg" ;						      \
   set -x ;								      \
   xcrun stapler staple "$$DMG" ;					      \
-  xcrun stapler validate "$$DMG"
+  xcrun stapler validate "$$DMG" ;					      \
 
 notarization_history::
 	xcrun altool --notarization-history 0 $(NOTARGS)
 	@echo 'now do: xcrun altool $(NOTARGS) --notarization-info <UUID>' ;  \
-	echo 'and wget the LogFileURL'
+	echo 'and wget the LogFileURL' ;				      \
 
 
 # When debugging, sometimes I have to reset the preferences for all
